name: C Build and Archive

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Compile code
      run: |
        cd .
        make

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-app
        path: .

