name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile code
        run: make
      - uses: actions/upload-artifact@v2
        with:
          name: compiled-app
          path: .
